dict_for_df = {"name": ["Tom", "Josue", "Miryam", "Latarsha", 
                        "Huan", "Klara", "Prasong", "Darius"],
               "age": [15, 33, 19, 45, 
                       60, 38, 29, 22], 
               "occupation": ["high school student", "alderman", "baker", "attorney", 
                              "accountant", "tutor", "server", "truck driver"], 
               "hours": [15, 24, 62, 88, 
                          8, 140, 12, 75],
               "city": ["San Francisco", "Millbrae", "San Francisco", "Daly City", 
                        "San Leandro", "San Francisco", "Daly City", "Oakland"]}
